apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 1m
  releaseName: kong
  chart:
    spec:
      chart: kong
      version: "2.37.0"  # 🔍 Check latest: https://artifacthub.io/packages/helm/kong/kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  values:
    ingressController:
      enabled: true
    proxy:
      type: LoadBalancer